# CMake initial cache for Switch Dawn build (Vulkan-only, static monolithic).
# Copied verbatim from KartPad-NX — same Dawn source, same target.
set(CMAKE_BUILD_TYPE Release CACHE STRING "" FORCE)
set(DAWN_BUILD_MONOLITHIC_LIBRARY STATIC CACHE STRING "" FORCE)
foreach(_option
    DAWN_ENABLE_VULKAN DAWN_ENABLE_PIC
    TINT_BUILD_AS_OTHER_OS TINT_BUILD_SPV_READER TINT_BUILD_SPV_WRITER
    TINT_BUILD_WGSL_READER TINT_BUILD_WGSL_WRITER)
  set(${_option} ON CACHE BOOL "" FORCE)
endforeach()
foreach(_option
    DAWN_WERROR DAWN_FETCH_DEPENDENCIES DAWN_ENABLE_D3D11 DAWN_ENABLE_D3D12 DAWN_ENABLE_METAL
    DAWN_ENABLE_DESKTOP_GL DAWN_ENABLE_OPENGLES DAWN_ENABLE_NULL
    DAWN_ENABLE_WEBGPU_ON_WEBGPU DAWN_ENABLE_SWIFTSHADER DAWN_ENABLE_INSTALL
    DAWN_BUILD_SAMPLES DAWN_BUILD_TESTS DAWN_BUILD_BENCHMARKS DAWN_BUILD_FUZZERS
    DAWN_BUILD_NODE_BINDINGS DAWN_BUILD_PROTOBUF DAWN_USE_GLFW
    DAWN_USE_X11 DAWN_USE_WAYLAND DAWN_USE_WINDOWS_UI DAWN_USE_BUILT_DXC
    TINT_BUILD_CMD_TOOLS TINT_BUILD_TESTS TINT_BUILD_BENCHMARKS
    TINT_BUILD_FUZZERS TINT_BUILD_IR_BINARY TINT_BUILD_GLSL_WRITER
    TINT_BUILD_HLSL_WRITER TINT_BUILD_MSL_WRITER TINT_BUILD_NULL_WRITER
    TINT_ENABLE_INSTALL)
  set(${_option} OFF CACHE BOOL "" FORCE)
endforeach()
